class Produto:
    def __init__(
        self,
        codigo_produto,
        descricao,
        subdescricao,
        produto_ativo,
        unidade_medida,
        itens_embalagem,
        codigo_barras,
        grupo,
        categoria,
        marca,
        itens_pallete,
        itens_lastro,
    ):
        self.codigo_produto = codigo_produto,
        self.descricao = descricao,
        self.subdescricao = subdescricao,
        self.produto_ativo = produto_ativo,
        self.unidade_medida = unidade_medida,
        self.itens_embalagem = itens_embalagem,
        self.codigo_barras = codigo_barras,
        self.grupo = grupo,
        self.categoria = categoria,
        self.marca = marca,
        self.itens_pallete = itens_pallete,
        self.itens_lastro = itens_lastro,
        self.quantidade_estoque = 0
